README: Allow updates to releases
[actions/create-release](https://github.com/actions/create-release) is archived and unmaintained. It still works, but I tried out another option that may be a better experience for others.

`create-release` works when the developer pushes a tag, but if a developer quickly creates a new release in the GitHub UI, it gives this error:

```
Run actions/create-release@v1
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

[ncipollo/release-action](https://github.com/ncipollo/release-action) has an allowUpdates options that solves this issue. A developer can create a new release in the GitHub UI, which will then be overwritten from the changelog.